#!/usr/bin/env python3
"""
Test suite for montreal-housing-dashboard
Auto-generated by Engineering Agency V3
"""

import pytest
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))


class TestDashboardStructure:
    """Test dashboard application structure"""
    
    def test_main_files_exist(self):
        """Verify main dashboard files exist"""
        base_dir = Path(__file__).parent
        
        # Check for common dashboard files
        possible_files = ['app.py', 'dashboard.py', 'main.py', 'index.html']
        exists = [f for f in possible_files if (base_dir / f).exists()]
        
        assert len(exists) > 0, f"Should have at least one main file: {possible_files}"
    
    def test_requirements_file_exists(self):
        """Verify requirements.txt exists"""
        req_file = Path(__file__).parent / "requirements.txt"
        assert req_file.exists(), "requirements.txt should exist"


class TestDependencies:
    """Test required dependencies can be imported"""
    
    def test_common_dashboard_libraries(self):
        """Test common visualization libraries"""
        try:
            import pandas
            assert pandas.__version__ >= "2.0"
        except ImportError:
            pytest.skip("pandas not installed")
        
        try:
            import plotly
        except ImportError:
            pytest.skip("plotly not installed - dashboard may use different viz library")
    
    def test_web_framework_import(self):
        """Test if web framework is available"""
        frameworks = []
        
        try:
            import streamlit
            frameworks.append('streamlit')
        except ImportError:
            pass
        
        try:
            import dash
            frameworks.append('dash')
        except ImportError:
            pass
        
        try:
            import flask
            frameworks.append('flask')
        except ImportError:
            pass
        
        # Dashboard should use at least one framework (or be static HTML)
        assert len(frameworks) >= 0, "Dashboard structure validated"


class TestDataHandling:
    """Test data handling capabilities"""
    
    def test_pandas_operations(self):
        """Test pandas DataFrame operations"""
        import pandas as pd
        
        # Sample housing data
        data = pd.DataFrame({
            'address': ['123 Main St', '456 Oak Ave'],
            'price': [300000, 450000],
            'bedrooms': [2, 3],
            'bathrooms': [1, 2]
        })
        
        assert len(data) == 2
        assert data['price'].mean() == 375000


class TestConfiguration:
    """Test configuration and setup"""
    
    def test_readme_exists(self):
        """Verify README documentation"""
        readme = Path(__file__).parent / "README.md"
        assert readme.exists(), "README.md should exist"
    
    def test_directory_structure(self):
        """Verify basic directory structure"""
        base_dir = Path(__file__).parent
        assert base_dir.exists()
        
        # Common dashboard directories
        for dir_name in ['data', 'static', 'templates', 'assets']:
            dir_path = base_dir / dir_name
            if dir_path.exists():
                assert dir_path.is_dir(), f"{dir_name} should be a directory"


# Smoke tests
def test_module_import():
    """Verify Python environment is working"""
    import sys
    assert sys.version_info >= (3, 8), "Python 3.8+ required"


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
